name: build wine
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build in Docker
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        echo "
        [multilib]
        Include = /etc/pacman.d/mirrorlist
        " >> /etc/pacman.conf
        useradd builduser -m
        passwd -d builduser
        pacman -Syu --noconfirm --needed sudo base-devel
        printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R builduser:builduser ./
        sudo -u builduser gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys CEFAC8EAAF17519D
        sudo -u builduser bash -c 'export MAKEFLAGS=j\$(nproc) && makepkg -s --noconfirm'
        EOF

        docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh

    - name: Upload Arch package
      uses: actions/upload-artifact@v2
      with:
        name: wine-staging-osxflags
        path: ${{ github.workspace }}/*.pkg.tar*
